# The SAP as an OmopStudyBuilder study directory -------------------------------
#
# OmopStudyBuilder::initStudy() lays out a study and leaves the analysis files
# EMPTY -- codelist/codelistCreation.R, cohorts/instantiateCohorts.R and
# analyses/*.R ship with no content. Those files are exactly what a SAP decides,
# so this renders them.
#
#   the harness owns   codeToRun.R (connection, schemas, library() calls,
#                                   min cell count) and runStudy.R (ordering,
#                                   logging, export). Both carry site-specific
#                                   credentials, so this NEVER writes them.
#   the SAP owns       the codelists, the cohorts, and the estimates.
#
# The harness's conventions differ from the standalone script the document's
# appendix shows: no library() header (codeToRun.R loads everything), no
# suppression block (runStudy.R applies the threshold once on export), estimates
# accumulate in `results[[...]]` for runStudy.R to bind, and every cohort gets
# CohortConstructor::addCohortTableIndex(). Every call still comes from
# sap_code.R, so the study directory and the appendix cannot describe different
# analyses. The codelist files are written from the content the SAP carries.

STUDY_PATHS <- list(
  codelists = "codelist/codelistCreation.R",
  cohorts   = "cohorts/instantiateCohorts.R",
  analyses  = "analyses/estimates.R"
)

# codelist/codelistCreation.R: every codelist a concept cohort uses, read from
# the files write_study_files() places under codelist/<name>/.
study_codelists_r <- function(sap) {
  cls <- used_codelists(sap)
  if (!length(cls)) {
    return("# No codelists: no concept cohort in this SAP uses one yet.\n")
  }
  blocks <- vapply(cls, function(cl) {
    sprintf("# %s\n%s", item_label(cl, "codelist"), codelist_r_code(cl) %||% "# (unknown codelist type)")
  }, character(1))
  paste0(paste(blocks, collapse = "\n\n"), "\n")
}

# cohorts/instantiateCohorts.R: every concept cohort, in order, each indexed.
study_cohorts_r <- function(sap) {
  blocks <- Filter(Negate(is.null), lapply(sap$cohorts %||% list(), function(co) {
    if (!identical(co$type, "concept_cohort")) return(NULL)
    block <- cohort_r_code(sap, co)
    tbl <- item_table_name(co)
    # An index on subject_id and cohort_start_date, the way every DARWIN study
    # adds one: a performance step, so it belongs in the code that runs and not
    # in the plan a reviewer signs. Inside the guard with the cohort it indexes.
    idx <- sprintf("\ncdm$%s <- cdm$%s |> CohortConstructor::addCohortTableIndex()", tbl, tbl)
    sprintf("# %s\n%s", item_label(co, "cohort"), source_guard(sap, paste0(block$code, idx), co))
  }))
  if (!length(blocks)) {
    return("# No concept cohorts: every cohort in this SAP is instantiated elsewhere.\n")
  }
  paste0(paste(unlist(blocks), collapse = "\n\n"), "\n")
}

# analyses/estimates.R: the denominator sets, then the estimates, accumulating
# into `results` for runStudy.R to bind and export.
study_analyses_r <- function(sap) {
  cohorts  <- sap$cohorts %||% list()
  analyses <- sap$analyses %||% list()
  out <- character(0)

  dens <- Filter(Negate(is.null), lapply(cohorts, function(co) {
    if (!is_denominator_type(co$type)) return(NULL)
    block <- cohort_r_code(sap, co)
    sprintf("# %s\n%s", item_label(co, "cohort"), source_guard(sap, block$code, co))
  }))
  if (length(dens)) {
    out <- c(out, paste0("# Denominator cohort sets ----\n\n", paste(unlist(dens), collapse = "\n\n")))
  }

  vars <- estimate_var_names(analyses)
  est <- lapply(seq_along(analyses), function(i) {
    a <- analyses[[i]]
    block <- analysis_r_code(sap, a)
    if (is.null(block)) {
      return(sprintf("# %s\n#   No estimator maps onto analysis type '%s'.",
                     item_label(a, "analysis"), as.character(a$type %||% "none")))
    }
    sprintf("# %s\n%s", item_label(a, "analysis"),
            source_guard_estimate(sap, sprintf('results[["%s"]]', vars[[i]]), block$code, a))
  })
  if (length(est)) out <- c(out, paste0("# Estimates ----\n\n", paste(unlist(est), collapse = "\n\n")))

  if (!length(out)) return("# No denominator cohort sets or estimates yet.\n")
  paste0(paste(out, collapse = "\n\n"), "\n")
}

# A header naming the SAP a file came from.
study_file_header <- function(sap, what) {
  study <- sap$study %||% list()
  sprintf(paste0(
    "# %s\n",
    "# Generated by shinySAP from the statistical analysis plan.\n",
    "#   Study:   %s\n",
    "#   Version: %s (SAP schema %s)\n",
    "# Edit the SAP and regenerate rather than editing this file: the plan a\n",
    "# reviewer signed and the code that runs are meant to be the same object.\n"),
    what,
    as.character(study$study_id %||% study$title %||% "unnamed"),
    as.character(study$version %||% "unversioned"),
    as.character(sap$sap_schema_version %||% "unknown"))
}

# Every script the SAP owns: relative path -> content.
study_files <- function(sap) {
  files <- list()
  files[[STUDY_PATHS$codelists]] <- paste0(study_file_header(sap, "Codelists"), "\n", study_codelists_r(sap))
  files[[STUDY_PATHS$cohorts]]   <- paste0(study_file_header(sap, "Study cohorts"), "\n", study_cohorts_r(sap))
  files[[STUDY_PATHS$analyses]]  <- paste0(study_file_header(sap, "Estimates"), "\n", study_analyses_r(sap))
  files
}

# What the SAP decides that lives in a file this must not write.
study_export_notes <- function(sap) {
  notes <- paste("Results are suppressed by runStudy.R on export; the SAP states no",
                 "threshold, so confirm the minimum cell count the data partners require.")
  restricted <- Filter(function(x) is_source_restricted(sap, x),
                       c(sap$cohorts %||% list(), sap$analyses %||% list()))
  if (length(restricted)) {
    notes <- c(notes, sprintf(paste(
      "%d cohorts or analyses are restricted to named databases, so the script",
      "guards them with omopgenerics::cdmName(cdm). Check that codeToRun.R",
      "creates the cdm reference with the same names this SAP uses (%s),",
      "or the guard will never be true and those steps will silently not run."),
      length(restricted), paste(sap_source_names(sap), collapse = ", ")))
  }
  paste(notes, collapse = " ")
}

# Write the scripts and the codelist files into a studyCode/ directory. Returns
# the paths written, invisibly. Creates missing directories but never removes
# anything: the target is a study skeleton with its own files.
write_study_files <- function(sap, dir) {
  files <- study_files(sap)
  paths <- character(0)
  for (rel in names(files)) {
    path <- file.path(dir, rel)
    dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
    writeLines(sub("\n+$", "", files[[rel]]), path)
    paths <- c(paths, path)
  }
  for (cl in used_codelists(sap)) {
    io <- codelist_io(cl$type)
    if (is.null(io) || is.null(cl$content)) next
    target <- file.path(dir, codelist_dir(cl))
    dir.create(target, recursive = TRUE, showWarnings = FALSE)
    getExportedValue("omopgenerics", io[["export"]])(cl$content, path = target, type = "json")
    paths <- c(paths, list.files(target, full.names = TRUE))
  }
  invisible(paths)
}
